### ISSUE TITLE
C++ docset

### ISSUE THREAD

**Issue by Travolter** [sunaku/dasht#32]
Could it be that there are issues with the C++ docset? 

First of all there seems to be an issue with the regex matcher to download the docset: 
```
» dasht-docsets-install c++
grep: repetition-operator operand invalid
```
And when I download + extract it manually I can succesfully start searching for things until I try to open a link:
`Can't load file:///Users/username/.local/share/dasht/docsets/C++.docset/Contents/Resources/Documents/<dash_entry_name=assign><dash_entry_originalName=std%3A%3Avector%3A%3Aassign><dash_entry_menuDescription=std%3A%3Avector%3A%3Aassign>en.cppreference.com/w/cpp/container/vector/assign.html#toc`

Am I doing something wrong?
I installed dasht using brew:  
```
» brew info dasht                
dasht: stable 2.2.0
```

**Comment by sunaku** [comment]
Extended regexp syntax is used by all of the dasht* tools, so you'll need to escape the plus signs like this:

```sh
dasht-docsets-install 'c\+\+'
```

I believe the `Can't load *` error you mentioned has been solved in master at commit 002fd4cdea802bea94c9073d6bd817c7da6e74dd. 

I guess it's high time for a new stable release. 😅  Please try the master branch for the time being.

**Comment by sunaku** [comment]
The patch is now released in v2.3.0 at https://github.com/sunaku/dasht/releases/tag/v2.3.0 :gift:

**Comment by FallenChromium** [comment]
Hm, this still occured to me on macOS with dasht version 2.4.0. The escape fix helped though, but I couldn't figure it out for a while, so a fix on the dasht's side would be appreciate it. Ping me if you'll need any additional info!
